version: "3.7"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
    - 3001:3000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus
    ports:
    - 9090:9090
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=1y'
    - '--web.enable-lifecycle'

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
    - 9100:9100
    command:
    - '--path.rootfs=/host'
    pid: host
    volumes:
    - '/:/host:ro,rslave'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
    - 8880:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    privileged: true
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - 9115:9115

  telegraf:
    image: telegraf:latest
          #    image: telegraf:1.16.3
    container_name: telegraf
    links:
      - influxdb
    networks:
      - monitoreo_default
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  influxdb:
    image: influxdb:latest
          #image: influxdb:1.8.3
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      - ./data_influxdb:/var/lib/influxdb
    networks:
      - monitoreo_default



#  influxdb:
#    image: influxdb:latest
#    container_name: influxdb
#    restart: always
#    networks: 
#      - monitoreo_default
#    ports:
#      - "8086:8086"
#    volumes:
#      - ./influxdb/data:/var/lib/influxdb
#      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
#      - ./influxdb/init:/docker-entrypoint-initdb.d
#    environment:
#      - INFLUXDB_ADMIN_USER=admin 
#      - INFLUXDB_ADMIN_PASSWORD=admin123 

#  telegraf:
#    image: telegraf:latest
#    restart: always
#    container_name: telegraf
#    networks: 
#      - monitoreo_default
#    volumes:
#      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro


volumes:
  grafana-data:
  prometheus-data:

networks:
  monitoreo_default:
    external: true

